package events

import (
	"context"

	"google.golang.org/protobuf/proto"
)

func ExampleClient_Publish() {
	ctx := context.Background()

	// Create a new events Client
	client, _ := NewClient(ctx)

	// Publish a message as the event.
	var message proto.Message // The message would typically be one of the autogenerated messages, say pb.Portfolio{}
	_ = client.Publish(ctx, message)
}
