package events

import (
	"context"
	"google.golang.org/protobuf/proto"
)

func ExampleNew() {

	ctx := context.Background()

	// Create a new pubsubClient
	client, _ := New("your-google-project", &Options{Topic: "my-topic"})

	// Publish a message as the event.
	var message proto.Message // The message would typically be one of the autogenerated messages, say pb.Portfolio{}
	_ = client.Publish(ctx, message, &PublishOptions{})
}
